In [19]:
import pandas as pd
import numpy as np

In [20]:
X = pd.read_csv('adult.data')

In [21]:
X.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [22]:
def sexToNum(str):
    return int(str == ' Female')
def incomeToNum(str):
    return int(str == ' >50K')

In [23]:
X['sex'] = X['sex'].apply(sexToNum)
X['income'] = X['income'].apply(incomeToNum)

In [24]:
X.shape

(32561, 15)

In [25]:
groups = X.groupby('sex')
observed = np.zeros((2,2), dtype=int)
expected = np.empty(observed.shape, dtype=float)

In [26]:
for i in range(2):
    g = groups.get_group(i)
    for j in range(len(g)):
        observed[g.iloc[j,:]['income']][i] += 1

In [27]:
for i in range(expected.shape[0]):
    for j in range(expected.shape[1]):
        expected[i][j] = (np.sum(observed, axis=1)[i] * np.sum(observed, axis=0)[j]) / np.sum(observed)

In [28]:
print(observed)
print(expected)
print(observed.sum())

[[15128  9592]
 [ 6662  1179]]
[[16542.75974325  8177.24025675]
 [ 5247.24025675  2593.75974325]]
32561


In [29]:
from scipy.stats import chisquare

In [30]:
chisquare(observed.ravel(), f_exp=expected.ravel())

Power_divergenceResult(statistic=1518.8868199570725, pvalue=0.0)

In [39]:
no_college = X[X['education-num'] < 11]
college = X[X['education-num'] >= 11]
X_temp = [no_college, college]
print(no_college.shape)
print(college.shape)

(22045, 15)
(10516, 15)


In [40]:
observed = np.zeros((2,2), dtype=int)
expected = np.empty(observed.shape, dtype=float)

In [41]:
for i in range(2):
    for j in range(len(X_temp[i])):
        observed[X_temp[i].iloc[j,:]['income']][i] += 1

In [42]:
for i in range(expected.shape[0]):
    for j in range(expected.shape[1]):
        expected[i][j] = (np.sum(observed, axis=1)[i] * np.sum(observed, axis=0)[j]) / np.sum(observed)

In [43]:
print(observed)
print(expected)
print(observed.sum())

[[18739  5981]
 [ 3306  4535]]
[[16736.3533061  7983.6466939]
 [ 5308.6466939  2532.3533061]]
32561


In [44]:
chisquare(observed.ravel(), f_exp=expected.ravel())

Power_divergenceResult(statistic=3081.2098533286526, pvalue=0.0)