In [1]:
import pandas as pd
import numpy as np

In [2]:
X = pd.read_table('titanic.txt')

In [3]:
X.head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  
0         1  
1         0  
2         0  
3         0  
4         1

In [4]:
def classToInt(str):
    return int(str[0])
def genderToInt(str):
    return int(str == 'female')

In [5]:
X['PClass'] = X['PClass'].apply(classToInt)
X['Sex'] = X['Sex'].apply(genderToInt)

In [6]:
X.head()

Name  PClass    Age  Sex  Survived
0                   Allen, Miss Elisabeth Walton       1  29.00    1         1
1                    Allison, Miss Helen Loraine       1   2.00    1         0
2            Allison, Mr Hudson Joshua Creighton       1  30.00    0         0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)       1  25.00    1         0
4                  Allison, Master Hudson Trevor       1   0.92    0         1

In [7]:
X.shape

(1313, 5)

In [8]:
groups = X.groupby('PClass')
print(len(groups))
observed = np.zeros((2,len(groups)), dtype=int)
expected = np.empty(observed.shape, dtype=int)
print(observed)

3
[[0 0 0]
 [0 0 0]]


In [9]:
print(observed)
for i in range(1,4):
    g = groups.get_group(i)
    for j in range(len(g)):
        observed[g.iloc[j,:]['Survived']][i-1] += 1

[[0 0 0]
 [0 0 0]]


In [10]:
for i in range(expected.shape[0]):
    for j in range(expected.shape[1]):
        expected[i][j] = (np.sum(observed, axis=1)[i] * np.sum(observed, axis=0)[j]) / np.sum(observed)

In [12]:
print(observed)
print(expected)

[[129 161 573]
 [193 119 138]]
[[211 184 467]
 [110  95 243]]


In [13]:
test_stat = ((observed - expected)**2 / expected).sum()
df = (expected.shape[0] - 1) * (expected.shape[1] - 1)

In [14]:
from scipy.stats import chisquare

In [15]:
chisquare(observed.ravel(), f_exp=expected.ravel())

Power_divergenceResult(statistic=172.86305674402652, pvalue=1.7871100449853575e-35)

In [16]:
groups = X.groupby('Sex')
print(len(groups))
observed = np.zeros((2,len(groups)), dtype=int)
expected = np.empty(observed.shape, dtype=float)
print(observed)

2
[[0 0]
 [0 0]]


In [17]:
for i in range(0,2):
    g = groups.get_group(i)
    print(len(g))
    for j in range(len(g)):
        observed[g.iloc[j,:]['Survived']][i] += 1

851
462


In [18]:
for i in range(expected.shape[0]):
    for j in range(expected.shape[1]):
        expected[i][j] = (np.sum(observed, axis=1)[i] * np.sum(observed, axis=0)[j]) / np.sum(observed)

In [19]:
print(observed)
print(expected)

[[709 154]
 [142 308]]
[[559.33968012 303.66031988]
 [291.66031988 158.33968012]]


In [109]:
chisquare(observed.ravel(), f_exp=expected.ravel())

Power_divergenceResult(statistic=332.05702407732934, pvalue=1.1444104478585824e-71)